### ISSUE TITLE
Could Submit Member Profile Twice

### ISSUE THREAD

**Issue by segsalerty2013** [forLoopOfficial/forLoop-website#5]
### Here 
[http://forloop.ng/members](http://forloop.ng/members)

Didn't submit though after re-auth. I see my profile info is empty for me to enter new profile info. Not like it pulled my previous data and wanted me to Update.

**Comment by walez** [comment]
Hello @segsalerty2013 
This has been fixed in an update, now it shows the modal with previous info populated,
So only the necessary info need be changed.
I will be closing this issue.
